//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:2.0.50727.8745
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gamma_mob.WCF
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IPrinterService
    {
        
        bool PrintPallet(string productId);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Xml.Serialization.XmlRootAttribute(ElementName="PrintPallet", Namespace="http://tempuri.org/")]
    public partial class PrintPalletRequest
    {
        
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string productId;
        
        public PrintPalletRequest()
        {
        }
        
        public PrintPalletRequest(string productId)
        {
            this.productId = productId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Xml.Serialization.XmlRootAttribute(ElementName="PrintPalletResponse", Namespace="http://tempuri.org/")]
    public partial class PrintPalletResponse
    {
        
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool PrintPalletResult;
        
        public PrintPalletResponse()
        {
        }
        
        public PrintPalletResponse(bool PrintPalletResult)
        {
            this.PrintPalletResult = PrintPalletResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class PrinterServiceClient : Microsoft.Tools.ServiceModel.CFClientBase<gamma_mob.WCF.IPrinterService>, gamma_mob.WCF.IPrinterService
    {
        
        public static System.ServiceModel.EndpointAddress EndpointAddress = new System.ServiceModel.EndpointAddress("http://192.168.0.53:8733/PrinterService/");
        
        public PrinterServiceClient() : 
                this(CreateDefaultBinding(), EndpointAddress)
        {
        }
        
        public PrinterServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
            addProtectionRequirements(binding);
        }
        
        private gamma_mob.WCF.PrintPalletResponse PrintPallet(gamma_mob.WCF.PrintPalletRequest request)
        {
            CFInvokeInfo info = new CFInvokeInfo();
            info.Action = "http://tempuri.org/IPrinterService/PrintPallet";
            info.RequestIsWrapped = true;
            info.ReplyAction = "http://tempuri.org/IPrinterService/PrintPalletResponse";
            info.ResponseIsWrapped = true;
            gamma_mob.WCF.PrintPalletResponse retVal = base.Invoke<gamma_mob.WCF.PrintPalletRequest, gamma_mob.WCF.PrintPalletResponse>(info, request);
            return retVal;
        }
        
        public bool PrintPallet(string productId)
        {
            PrintPalletRequest request = new PrintPalletRequest(productId);
            PrintPalletResponse response = this.PrintPallet(request);
            return response.PrintPalletResult;
        }
        
        public static System.ServiceModel.Channels.Binding CreateDefaultBinding()
        {
            System.ServiceModel.Channels.CustomBinding binding = new System.ServiceModel.Channels.CustomBinding();
            binding.Elements.Add(new System.ServiceModel.Channels.TextMessageEncodingBindingElement(System.ServiceModel.Channels.MessageVersion.Soap11, System.Text.Encoding.UTF8));
            binding.Elements.Add(new System.ServiceModel.Channels.HttpTransportBindingElement());
            return binding;
        }
        
        private void addProtectionRequirements(System.ServiceModel.Channels.Binding binding)
        {
            if ((IsSecureMessageBinding(binding) == false))
            {
                return;
            }
            System.ServiceModel.Security.ChannelProtectionRequirements cpr = new System.ServiceModel.Security.ChannelProtectionRequirements();
            ApplyProtection("http://tempuri.org/IPrinterService/PrintPallet", cpr.IncomingSignatureParts, true);
            ApplyProtection("http://tempuri.org/IPrinterService/PrintPallet", cpr.IncomingEncryptionParts, true);
            if ((binding.MessageVersion.Addressing == System.ServiceModel.Channels.AddressingVersion.None))
            {
                ApplyProtection("*", cpr.OutgoingSignatureParts, true);
                ApplyProtection("*", cpr.OutgoingEncryptionParts, true);
            }
            else
            {
                ApplyProtection("http://tempuri.org/IPrinterService/PrintPalletResponse", cpr.OutgoingSignatureParts, true);
                ApplyProtection("http://tempuri.org/IPrinterService/PrintPalletResponse", cpr.OutgoingEncryptionParts, true);
            }
            this.Parameters.Add(cpr);
        }
    }
}
